steps:
# build the container image
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'root@my-instance-vm'
  - '--zone'
  - 'us-central1-c'
  - '--command'
  - |
    gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
    gcloud compute ssh my-instance-vm --project=develop-375210 --zone=us-central1-c --strict-host-key-checking=no
    ssh root@my-instance-vm ls /home/saba/main.go
    ssh root@my-instance-vm "cd /home/saba && go build main.go"

