steps:
# build the container image
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'scp'
  - 'github.com/Saba1119/crudapp-cloudbuild/main.go'
  - 'root@my-instance-vm:/home/saba'
  - '--zone'
  - 'us-central1-c'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'root@my-instance-vm'
  - '--zone'
  - 'us-central1-c'
  - '--command'
  - |
    ls /home/saba/main.go
    cd /home/saba
    go build main.go
