steps:
# build the container image
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'root@my-instance-vm'
  - '--zone'
  - 'us-central1-c'
  - '--command'
  - |
    gcloud auth print-access-token 
    gcloud compute scp main.go root@my-instance-vm:/home/saba --zone=us-central1-c
    gcloud compute ssh root@my-instance-vm ls /home/saba/main.go
    gcloud compute ssh root@my-instance-vm "cd /home/saba && go build main.go"

