- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'root@my-instance-vm'
  - '--zone'
  - 'us-central1-c'
  - '--command'
  - |
    # Authenticate with Docker using the access token obtained from gcloud
    gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
    
    # Copy the main.go file to the VM instance using the gcloud compute scp command
    gcloud compute scp main.go root@my-instance-vm:/home/saba --zone=us-central1-c
    
    # Check that the file was copied over successfully
    ssh root@my-instance-vm ls /home/saba/main.go
    
    # Build the Go application by running the go build command in the directory where main.go is located
    ssh root@my-instance-vm "cd /home/saba && go build main.go"

